# Addin play
# Install memcached
---
- name: "Remove memcached from ssh."
  include_role:
    name: apnscp/initialize-filesystem-template
    tasks_from: "remove-package.yml"
  vars:
    package: memcached
- name: "Install memcached package."
  include_role:
    name: apnscp/initialize-filesystem-template
    tasks_from: "install-package.yml"
  vars:
    package: memcached
    service: siteinfo
- name: "Get existing pecl_extensions."
  shell: |
    cpcmd -o json scope:get cp.bootstrapper pecl_extensions
  register: r
- name: "Parse existing and set required pecl_extensions."
  set_fact:
    pecl_extensions: "{{ r.stdout | from_json }}"
    pecl_extensions_updated: []
- set_fact:
    pecl_extensions: []
  when: (pecl_extensions | type_debug not in ['list', 'string']) or pecl_extensions == ''
- name: "Add required pecl_extensions."
  set_fact:
    pecl_extensions: |
      {{
        (pecl_extensions | type_debug == 'list') | ternary(pecl_extensions, [pecl_extensions]) + [ 'memcached' ]
      }}
  when: "'memcached' not in pecl_extensions"
- name: "Set pecl_extensions via cpcmd."
  shell: |
    cpcmd scope:set cp.bootstrapper pecl_extensions '{{pecl_extensions|to_json}}'
